name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  commands:
    description: 'arguments to be passed'
    required: true
  parallel:
    description: 'run commands in parallel'
    default: false
  github-token:
    description: 'a workaround for running in macos'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
