name: 'mask-action'
description: 'Github Action for running (or just install) "mask" task runner'
author: 'Fahmi Akbar Wildana <sensorfied@gmail.com>'
branding:
  icon: "terminal"
  color: "gray-dark"


inputs:
  commands:
    description: 'arguments to be passed'
    required: true
  parallel:
    description: 'run commands in parallel'
    default: false
  github-token:
    description: 'a workaround for running in macos'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
